resolve conflicts
vanmarkic/touchepas pull request #35
Opened 2024-01-22 18:39 UTC by aurorevd

2024-01-22 18:40 UTC, aurorevd commented
tu peux merge?

2024-01-22 20:04 UTC, vanmarkic commented
je ne peux pas merge en l'état car 
![image](https://github.com/vanmarkic/touchepas/assets/37640579/a40983c9-1247-460e-9543-08a955aec0b0)

2024-01-22 20:20 UTC, vanmarkic requested changes
pas mal de petites choses à résoudre avant de merge, n'hésite pas si tu as besoin d'aide ou d'un moment de pair programming :)

2024-01-22 20:20 UTC, vanmarkic commented on src/components/layout.tsx
> +  const [showMobileMenu, setShowMobileMenu] = React.useState(false);
à enlever, non utilisé

2024-01-22 20:20 UTC, vanmarkic commented on src/components/layout.tsx
> +            <img alt='wallonie' src='../images/wallonie.png' />
il vaut mieux utiliser <StaticImage> fourni par gatsby. Pour plein de bonnes raisons difficile à expliquer ici

2024-01-22 20:20 UTC, vanmarkic commented on src/pages/index.tsx
> +    <IntroSection/>
est-ce vraiment voulu ?

2024-01-22 20:20 UTC, vanmarkic commented on src/pages/index.tsx
> +        Infos utiles
ok, mais alors il faut aussi changer le titres de la section plus bas

2024-01-22 20:20 UTC, vanmarkic commented on src/styles/global.ts
> +.scrolled {
à quoi sert cette classe ? je ne la vois utilsée nulle part...

2024-01-22 20:20 UTC, vanmarkic commented on src/styles/global.ts
> +  .logo {
ceci est mieux :
```
const StyledStaticImage = styled(StaticImage)'
  height: fit-content;
  height: 12vw !important;
  width: 12vw !important;
  @media (max-aspect-ratio: 1/1) and (max-width: 759px) {
    width: 20vw !important;
    height: 20vw !important;
  }
';

export const IntroSection = () => (
  <div style={{ display: 'flex', flexDirection: 'column', width: '80%' }}>
    <FlexDiv>
      <BigTitle>
        TOUCHE <span> PAS </span>À MON LOYER
      </BigTitle>
      <StyledStaticImage
        alt="a building with apartments"
        placeholder="none"
        layout="fixed"
        src={'../logo/favicon/android-chrome-512x512.png'}
        loading="eager"
      />```
car on comprend directement à quoi est utilisée la classe css

2024-01-23 08:33 UTC, aurorevd commented on src/components/layout.tsx
> +  const [showMobileMenu, setShowMobileMenu] = React.useState(false);
ok

2024-01-23 08:33 UTC, aurorevd commented on src/pages/index.tsx
> +    <IntroSection/>
oui

2024-01-23 08:33 UTC, aurorevd commented on src/pages/index.tsx
> +        Infos utiles
ok

2024-01-23 08:34 UTC, aurorevd commented on src/styles/global.ts
> +.scrolled {
delete

2024-01-23 08:34 UTC, aurorevd commented on src/styles/global.ts
> +  .logo {
ok

2024-01-23 08:34 UTC, closed without merging